### ISSUE TITLE
Intermittently failing spec

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#1771]
This spec is failing intermittently; it looks like the workflow states are getting hit in a different order sometimes and so the body is mixed up.

https://github.com/pulibrary/figgy/blob/87052a78a086b13a9bbc2ea243ee4e41ad63f372/spec/mailers/collections_mailer_spec.rb#L8-L25

here's an example of a failed run: 
```
  1) CollectionsMailer owner_report works
     Failure/Error: expect(email.body.to_s).to eq expected_body(ids: [r1.id, r2.id, r3.id])
     
       expected: "<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charse...cedb3ce14\">Pretty Resource</a>\n      </li>\n    </ul>\n  </body>\n</html>\n\n  </body>\n</html>\n"
            got: "<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charse...urally Significant Resource</a>\n      </li>\n    </ul>\n  </body>\n</html>\n\n  </body>\n</html>\n"
     
       (compared using ==)
     
       Diff:
       @@ -15,6 +15,12 @@
          </head>
          <body>
            <h2>Weekly collection report for The Important Person&#39;s Things</h2>
       +    <p>Resources in workflow state "final review"</p>
       +    <ul>
       +      <li>
       +        <a href="http://www.example.com/catalog/b755c2a4-17db-48d7-b631-2aacedb3ce14?utm_campaign=build-failed&utm_medium=email&utm_source=notification">Pretty Resource</a>
       +      </li>
       +    </ul>
            <p>Resources in workflow state "pending"</p>
            <ul>
              <li>
       @@ -22,12 +28,6 @@
              </li>
              <li>
                <a href="http://www.example.com/catalog/c77817d3-359c-46d7-9183-47a41182058f?utm_campaign=build-failed&utm_medium=email&utm_source=notification">Culturally Significant Resource</a>
       -      </li>
       -    </ul>
       -    <p>Resources in workflow state "final review"</p>
       -    <ul>
       -      <li>
       -        <a href="http://www.example.com/catalog/b755c2a4-17db-48d7-b631-2aacedb3ce14?utm_campaign=build-failed&utm_medium=email&utm_source=notification">Pretty Resource</a>
              </li>
            </ul>
          </body>
       
     # ./spec/mailers/collections_mailer_spec.rb:22:in `block (3 levels) in <top (required)>'

Finished in 10 minutes 48 seconds (files took 38.71 seconds to load)
2721 examples, 1 failure, 39 pending

Failed examples:

rspec ./spec/mailers/collections_mailer_spec.rb:8 # CollectionsMailer owner_report works

Randomized with seed 23327
```

**Comment by hackmastera** [comment]
Here's another example of failure on this spec:
```
Failures:

  1) CollectionsMailer owner_report works
     Failure/Error: expect(email.body.to_s).to eq expected_body(ids: [r1.id, r2.id, r3.id])
     
       expected: "<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charse...1c71688ce\">Pretty Resource</a>\n      </li>\n    </ul>\n  </body>\n</html>\n\n  </body>\n</html>\n"
            got: "<!DOCTYPE html>\n<html>\n  <head>\n    <meta http-equiv=\"Content-Type\" content=\"text/html; charse...1c71688ce\">Pretty Resource</a>\n      </li>\n    </ul>\n  </body>\n</html>\n\n  </body>\n</html>\n"
     
       (compared using ==)
     
       Diff:
       
       @@ -18,10 +18,10 @@
            <p>Resources in workflow state "pending"</p>
            <ul>
              <li>
       -        <a href="http://www.example.com/catalog/48ab11d5-d5e0-4a21-baa7-9407098b3a87">Historically Significant Resource</a>
       +        <a href="http://www.example.com/catalog/c9ceb354-c7da-41c5-b281-d25cc531a287">Culturally Significant Resource</a>
              </li>
              <li>
       -        <a href="http://www.example.com/catalog/c9ceb354-c7da-41c5-b281-d25cc531a287">Culturally Significant Resource</a>
       +        <a href="http://www.example.com/catalog/48ab11d5-d5e0-4a21-baa7-9407098b3a87">Historically Significant Resource</a>
              </li>
            </ul>
            <p>Resources in workflow state "final review"</p>
       
     # ./spec/mailers/collections_mailer_spec.rb:22:in `block (3 levels) in <top (required)>'

Finished in 7 minutes 49 seconds (files took 34.91 seconds to load)
2787 examples, 1 failure, 35 pending

Failed examples:

rspec ./spec/mailers/collections_mailer_spec.rb:8 # CollectionsMailer owner_report works

Randomized with seed 4299
```
