### ISSUE TITLE
Periodic test failures accessing helper from decorator

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#1854]
```
Failures:

  1) EventGenerator::GeoblacklightEventGenerator#record_member_updated with a record in a completed state publishes a persistent JSON updated message with geoblacklight document
     Failure/Error: h.visibility_badge(visibility)
     
     NoMethodError:
       undefined method `visibility_badge' for #<#<Class:0x000000001c419fa8>:0x000000001e84f9b8>
     # ./app/decorators/valkyrie/resource_decorator.rb:48:in `block in visibility'
     # ./app/decorators/valkyrie/resource_decorator.rb:47:in `map'
     # ./app/decorators/valkyrie/resource_decorator.rb:47:in `visibility'
     # ./app/decorators/application_decorator.rb:39:in `[]'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:27:in `block in direct_attributes'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:26:in `map'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:26:in `direct_attributes'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:18:in `merged_attributes'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:13:in `merged_attributes_object'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:35:in `block in build_simple_attributes'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:34:in `each'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:34:in `build_simple_attributes'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:14:in `build'
     # ./app/services/geo_discovery/document_builder/composite_builder.rb:15:in `block in build'
     # ./app/services/geo_discovery/document_builder/composite_builder.rb:14:in `each'
     # ./app/services/geo_discovery/document_builder/composite_builder.rb:14:in `build'
     # ./app/services/geo_discovery/document_builder.rb:33:in `initialize'
     # ./spec/services/event_generator/geoblacklight_event_generator_spec.rb:72:in `new'
     # ./spec/services/event_generator/geoblacklight_event_generator_spec.rb:72:in `block (4 levels) in <top (required)>'

  2) EventGenerator::GeoblacklightEventGenerator#record_updated with a record in a completed state publishes a persistent JSON updated message with geoblacklight document
     Failure/Error: h.visibility_badge(visibility)
     
     NoMethodError:
       undefined method `visibility_badge' for #<#<Class:0x000000001c419fa8>:0x000000001e84f9b8>
     # ./app/decorators/valkyrie/resource_decorator.rb:48:in `block in visibility'
     # ./app/decorators/valkyrie/resource_decorator.rb:47:in `map'
     # ./app/decorators/valkyrie/resource_decorator.rb:47:in `visibility'
     # ./app/decorators/application_decorator.rb:39:in `[]'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:27:in `block in direct_attributes'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:26:in `map'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:26:in `direct_attributes'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:18:in `merged_attributes'
     # ./app/decorators/geoblacklight_metadata_decorator.rb:13:in `merged_attributes_object'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:35:in `block in build_simple_attributes'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:34:in `each'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:34:in `build_simple_attributes'
     # ./app/services/geo_discovery/document_builder/basic_metadata_builder.rb:14:in `build'
     # ./app/services/geo_discovery/document_builder/composite_builder.rb:15:in `block in build'
     # ./app/services/geo_discovery/document_builder/composite_builder.rb:14:in `each'
     # ./app/services/geo_discovery/document_builder/composite_builder.rb:14:in `build'
     # ./app/services/geo_discovery/document_builder.rb:33:in `initialize'
     # ./spec/services/event_generator/geoblacklight_event_generator_spec.rb:29:in `new'
     # ./spec/services/event_generator/geoblacklight_event_generator_spec.rb:29:in `block (4 levels) in <top (required)>'

Finished in 7 minutes 24 seconds (files took 16.35 seconds to load)
2792 examples, 2 failures, 35 pending

Failed examples:

rspec ./spec/services/event_generator/geoblacklight_event_generator_spec.rb:71 # EventGenerator::GeoblacklightEventGenerator#record_member_updated with a record in a completed state publishes a persistent JSON updated message with geoblacklight document
rspec ./spec/services/event_generator/geoblacklight_event_generator_spec.rb:28 # EventGenerator::GeoblacklightEventGenerator#record_updated with a record in a completed state publishes a persistent JSON updated message with geoblacklight document

Randomized with seed 14954
```

**Comment by jrgriffiniii** [comment]
I've also encountered this earlier today when running tests on CircleCI, hence it's still being occasionally triggered.

**Comment by hackmastera** [comment]
possibly related to https://github.com/drapergem/draper/issues/655 ? Maybe we should clear draper view context between specs?

**Comment by hackmastera** [comment]
This is still happening.
