### ISSUE TITLE
"Record [...] not found or suppressed" responses for remote metadata requests should respond with a UI alert

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#1930]
Currently, the following error simply triggers a 500 error for users attempting to create a new resource with imported metadata:

```
MultiJson::ParseError (765: unexpected token at 'Record 32101047381 not found or suppressed'):

app/models/remote_record.rb:65:in `jsonld'
app/models/remote_record.rb:55:in `attributes'
app/models/archival_media_bag_parser.rb:143:in `remote_record_attributes'
app/models/archival_media_bag_parser.rb:147:in `remote_record_source_metadata'
app/models/archival_media_bag_parser.rb:153:in `xml'
app/models/archival_media_bag_parser.rb:159:in `barcode_nodes'
app/models/archival_media_bag_parser.rb:132:in `parse_dict!'
app/models/archival_media_bag_parser.rb:117:in `initialize'
app/models/archival_media_bag_parser.rb:10:in `new'
app/models/archival_media_bag_parser.rb:10:in `initialize'
app/validators/unique_archival_media_barcode_validator.rb:48:in `new'
app/validators/unique_archival_media_barcode_validator.rb:48:in `bag'
app/validators/unique_archival_media_barcode_validator.rb:32:in `files_to_import'
app/validators/unique_archival_media_barcode_validator.rb:26:in `duplicates'
app/validators/unique_archival_media_barcode_validator.rb:19:in `validate!'
app/validators/unique_archival_media_barcode_validator.rb:9:in `validate'
app/controllers/concerns/resource_controller.rb:23:in `create'
```

**Comment by tpendragon** [comment]
Just tested, this is fixed.
