### ISSUE TITLE
Full reindex failing on production

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/figgy#2150]
There have been several challenges here, most recently a memory problem resolved by https://github.com/pulibrary/figgy/pull/2146 which has successfully run on staging.

Now we're seeing an undefined method on `ModelConverter::Property`

```
NoMethodError: undefined method `apply_to' for #<Valkyrie::Persistence::Solr::ModelConverter::Property:0x00000000051f4e38>
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:188:in `block in apply_to'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:187:in `each'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:187:in `apply_to'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:113:in `block in attribute_hash'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:105:in `each'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:105:in `each_with_object'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:105:in `attribute_hash'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:54:in `to_h'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/model_converter.rb:21:in `convert!'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/resource_factory.rb:28:in `from_resource'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/repository.rb:59:in `solr_document'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/repository.rb:24:in `block in persist'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/repository.rb:22:in `map'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/repository.rb:22:in `persist'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/valkyrie-1.2.2/lib/valkyrie/persistence/solr/persister.rb:35:in `save_all'
/opt/figgy/releases/20181112195325/app/adapters/instrumented_adapter.rb:94:in `block in save_all'
/opt/figgy/releases/20181112195325/app/adapters/instrumented_adapter.rb:48:in `block in trace'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/ddtrace-0.16.0/lib/ddtrace/tracer.rb:296:in `trace'
/opt/figgy/releases/20181112195325/app/adapters/instrumented_adapter.rb:44:in `trace'
/opt/figgy/releases/20181112195325/app/adapters/instrumented_adapter.rb:93:in `save_all'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:30:in `block in reindex_all'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/dataset/actions.rb:151:in `yield'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/dataset/actions.rb:151:in `block in each'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:609:in `block in fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:734:in `block (3 levels) in cursor_fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:734:in `yield_hash_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:734:in `block (2 levels) in cursor_fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:142:in `execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:496:in `_execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel_pg-1.11.0/lib/sequel/extensions/pg_streaming.rb:47:in `_execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:314:in `block (2 levels) in execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:518:in `check_database_errors'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:314:in `block in execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/connection_pool/threaded.rb:87:in `hold'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/connecting.rb:253:in `synchronize'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:314:in `execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/dataset/actions.rb:1083:in `execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/ddtrace-0.16.0/lib/ddtrace/contrib/sequel/dataset.rb:17:in `block in execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/ddtrace-0.16.0/lib/ddtrace/contrib/sequel/dataset.rb:47:in `block in trace_execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/ddtrace-0.16.0/lib/ddtrace/tracer.rb:296:in `trace'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/ddtrace-0.16.0/lib/ddtrace/contrib/sequel/dataset.rb:42:in `trace_execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/ddtrace-0.16.0/lib/ddtrace/contrib/sequel/dataset.rb:17:in `execute'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:732:in `block in cursor_fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/transactions.rb:204:in `_transaction'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/transactions.rb:179:in `block in transaction'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/connecting.rb:253:in `block in synchronize'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/connection_pool/threaded.rb:91:in `hold'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/connecting.rb:253:in `synchronize'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/database/transactions.rb:145:in `transaction'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:725:in `public_send'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:725:in `cursor_fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/adapters/postgres.rb:609:in `fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel_pg-1.11.0/lib/sequel/extensions/pg_streaming.rb:116:in `fetch_rows'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel-5.13.0/lib/sequel/dataset/actions.rb:151:in `each'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/sequel_pg-1.11.0/lib/sequel_pg/sequel_pg.rb:81:in `each'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:28:in `each'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:28:in `each'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:28:in `each'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:28:in `each_slice'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:28:in `reindex_all'
/opt/figgy/releases/20181112195325/app/services/reindexer.rb:10:in `reindex_all'
/opt/figgy/releases/20181112195325/lib/tasks/reindex.rake:8:in `block in <top (required)>'
/opt/figgy/shared/bundle/ruby/2.4.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
Tasks: TOP => reindex
(See full trace by running task with --trace)
```

**Comment by tpendragon** [comment]
:sob: So this is usually because we have a value in a postgres object that the solr adapter doesn't know how to convert.

**Comment by tpendragon** [comment]
It looks like `ocr_content` is set to a symbol on some FileSets.

**Comment by tpendragon** [comment]
```
figgy_production=# select COUNT(*) FROM orm_resources WHERE metadata->>'ocr_content' LIKE '[":%';
 count
-------
   550
```

**Comment by tpendragon** [comment]
https://github.com/samvera-labs/valkyrie-sequel/pull/11 Okay. So the problem was `Oj` in non-compat mode interprets a string that starts with a colon as a symbol. That PR fixes the bug.

**Comment by hackmastera** [comment]
I'm still running the resource factory but have found at least 2 filesets still causing problems. looked at one of them and the problem may be that `ocr_content` starts with lots of colons. `":::::::::§\\\nadicionales de atencién`

ids are `958923fb-f07a-45f0-b049-c7ac18a8aff0`, `df8a45fb-c7f1-44ff-b566-440089d62868`

**Comment by hackmastera** [comment]
yep both of them are like that so it seems likely that's the issue. tried to write a test in valkyrie-sequel but had trouble with test setup; https://github.com/samvera-labs/valkyrie-sequel/issues/12

**Comment by tpendragon** [comment]
Those ones are still returning as symbols for the string?

**Comment by hackmastera** [comment]
they are still triggering the `NoMethodError`. I tried to answer that question by writing a test in valkyrie-sequel but i had trouble with test setup. that's what i've done so far.

**Comment by hackmastera** [comment]
perhaps the colons cause an issue higher up in the stack
```
> Oj.load(bad_json, create_additions: false, mode: :compat)
=> {"ocr"=>":::::::::§\\\n" + "adicionales de atencién"}
```

**Comment by tpendragon** [comment]
Weird, if I run 958923fb-f07a-45f0-b049-c7ac18a8aff0 through the solr resource factory on the command line it seems to go through fine

**Comment by hackmastera** [comment]
It finished!!!!!!
