### ISSUE TITLE
Builds fail for user authentication with Net::ReadTimeout

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#265]
In some cases, test builds fail on CircleCI with the following message:
```
1) Ephemera Terms when users have added a controlled vocabulary when users have added terms to the vocabulary users can edit existing terms
     Failure/Error: visit user_cas_omniauth_authorize_path
     
     Net::ReadTimeout:
       Net::ReadTimeout
     # ./spec/support/features/session_helpers.rb:12:in `sign_in'
     # ./spec/features/ephemera_terms_spec.rb:13:in `block (2 levels) in <top (required)>'
```

**Comment by jrgriffiniii** [comment]
Unfortunately, there isn't any truly effective method of testing this, but I suspect that the requests sent to the external CAS provider was triggering the timeouts.
