### ISSUE TITLE
Periodic Test Failure - BulkEditController UserID

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#2662]
```
  1) BulkEditController POST /bulk_edit when there are multiple pages of results enqueues one update job per page of results
     Failure/Error: expect(BulkUpdateJob).to have_been_enqueued.with(ids: [resource1.id.to_s], args: { mark_complete: true })
     
     ActiveJob::DeserializationError:
       Error while trying to deserialize arguments: Couldn't find User with 'id'=55
     # ./spec/controllers/bulk_edit_controller_spec.rb:45:in `block (4 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # ActiveRecord::RecordNotFound:
     #   Couldn't find User with 'id'=55
     #   ./spec/controllers/bulk_edit_controller_spec.rb:45:in `block (4 levels) in <top (required)>'
```

**Comment by christinach** [comment]
I've seen this as well

**Comment by eliotjordan** [comment]
Ran an rspec --bisect on this:

```
The minimal reproduction command is:
  rspec './spec/controllers/bulk_edit_controller_spec.rb[1:2:2:1]' './spec/resources/archival_media_collections/archival_media_collections_controller_spec.rb[1:2:2:1]' --seed 25219
```
