### ISSUE TITLE
Requesting IIIF Manifests for EphemeraFolders fail

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/figgy#274]
Discovered by @escowles while testing within the staging environment

**Comment by escowles** [comment]
In the console I see:

```
ArgumentError (wrong number of arguments (given 0, expected 1)):
  
app/decorators/application_decorator.rb:29:in `attributes'
app/services/manifest_builder/faster_iiif_manifest.rb:9:in `to_json'
app/services/manifest_builder.rb:15:in `build'
app/controllers/ephemera_folders_controller.rb:47:in `block (2 levels) in manifest'
app/controllers/ephemera_folders_controller.rb:45:in `manifest'
```
