### ISSUE TITLE
Periodic Test Failure 

### ISSUE THREAD

**Issue by christinach** [pulibrary/figgy#3103]
```Failures:

  1) Ephemera Vocabularies when users visit a project when users have added a field and a box users can edit folder metadata with controlled vocabularies
     Failure/Error: visit user_cas_omniauth_authorize_path
     
     Net::OpenTimeout:
       execution expired
     # ./spec/support/features/session_helpers.rb:13:in `sign_in'
     # ./spec/resources/ephemera_vocabularies/ephemera_vocabularies_feature_spec.rb:13:in `block (2 levels) in <top (required)>'

Finished in 2 minutes 45.2 seconds (files took 11.1 seconds to load)
792 examples, 1 failure, 4 pending

Failed examples:

rspec ./spec/resources/ephemera_vocabularies/ephemera_vocabularies_feature_spec.rb:67 # Ephemera Vocabularies when users visit a project when users have added a field and a box users can edit folder metadata with controlled vocabularies
```

**Comment by escowles** [comment]
Has anyone seen this failure recently?

**Comment by escowles** [comment]
Closing for now — if anyone has, we can reopen this.
