### ISSUE TITLE
find_number/issue_number/coin_number/accession_number should be Valkyrie::Types::Coercible::Integer

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4728]
Right now they're persisting as strings because they're coming out of a form.

See #4726 for background info.

This could include a migration to convert those string values to integers.

**Comment by hackartisan** [comment]
The merged PR had to be reverted; I pushed the 4728-coin-accession branch again so we can work more on this.

Error observed on staging after deploy prevented the migration from running. A replication of the error: 
```
irb(main):013:0> r = query_service.find_all_of_model(model: Numismatics::Coin).last
Traceback (most recent call last):
        6: from (irb):13
        5: from (irb):13:in `rescue in irb_binding'
        4: from app/adapters/instrumented_adapter.rb:141:in `find_all_of_model'
        3: from app/adapters/instrumented_adapter.rb:44:in `trace'
        2: from app/adapters/instrumented_adapter.rb:48:in `block in trace'
        1: from app/adapters/instrumented_adapter.rb:143:in `block in find_all_of_model'
Dry::Struct::Error ([Numismatics::Coin.new] [] (Array) has invalid type for :find_number violates constraints (can't convert Array into Integer failed))
```

**Comment by hackartisan** [comment]
I took a look at the data and find number definitely can have alpha characters

**Comment by hackartisan** [comment]
reopening until we've run the migration

**Comment by hackartisan** [comment]
migration is finished
