### ISSUE TITLE
CDL Early Return is throwing errors on a regular basis.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4755]
## Backtrace

    line 75 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in save
    line 48 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: block in trace
    line 44 of [PROJECT_ROOT]/app/adapters/instrumented_adapter.rb: trace
    
## Params

```ruby
{
  "id" => "4494f3c3-9535-4445-b08a-4dd15c270e4b",
  "controller" => "cdl/cdl",
  "action" => "charge"
}
```

## Full Backtrace

```
app/adapters/instrumented_adapter.rb:75:in `block in save'
app/adapters/instrumented_adapter.rb:48:in `block in trace'
app/adapters/instrumented_adapter.rb:44:in `trace'
app/adapters/instrumented_adapter.rb:74:in `save'
app/change_set_persisters/change_set_persister.rb:99:in `save'
app/resources/cdl/charge_manager.rb:49:in `create_charge'
app/resources/cdl/cdl_controller.rb:13:in `charge'
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/67197483)

**Comment by tpendragon** [comment]
In the most recent case it looks like someone hit the checkout button twice.

**Comment by tpendragon** [comment]
It seems like someone's slamming that button a bunch too and managing to take up all the available item charges for themselves.

**Comment by tpendragon** [comment]
We may have solved this. I've resolved the CDL ticket and I'm marking this closed. We should reopen this if honeybadger errors about it again.
