### ISSUE TITLE
RunOCRJob should not error if the file is gone

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/figgy#4972]
## Backtrace

    line 29 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in find_by
    line 50 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: block in trace
    line 45 of [PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb: trace
    
 ## Full Backtrace

```
Valkyrie::StorageAdapter::FileNotFound:[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-fbb86f933dd8ac6737066cb9a1401dd9-cf7cb6cbb2c3)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/storage_adapters/instrumented_storage_adapter.rb#L29)Valkyrie::StorageAdapter::FileNotFound
[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-abde96fc8ac1d8778c59ab1a1fe6dcd8-b075551db4fc)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/storage_adapters/instrumented_storage_adapter.rb#L50)instrumented_storage_adapter.rb[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-f6dc64cfa4c3823a056ee678803f6ba4-6b16066a11b8)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/storage_adapters/instrumented_storage_adapter.rb#L45)[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-90414aa5e58714c60f02f15c87a649f9-46ea915c399c)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/storage_adapters/instrumented_storage_adapter.rb#L27)29[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-750a8652351e3eff698ae5aa5d67297e-8bb8f28fc262)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/derivative_services/hocr_derivative_service.rb#L60)[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-b9f260e4714f39af9a8732ac264639f3-a75bddef6933)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/derivative_services/hocr_derivative_service.rb#L56)block[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-cd70a627559c72c0b68c2b332c49bcaf-bb33bb5fb000)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/derivative_services/hocr_derivative_service.rb#L26)in[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-2165af21f272dce458f8032fa6cf70fe-3c14379f0dda)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/derivative_services/hocr_derivative_service.rb#L13)find_by(...)
[PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb:29:in[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-2165af21f272dce458f8032fa6cf70fe-7d39ba2260ea)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/derivative_services/hocr_derivative_service.rb#L13)`block[ ](https://app.honeybadger.io/projects/53391/faults/83759049#backtrace-line-42d2d921aee0efa00f907cdb541bafac-9f929c095c45)[](https://github.com/pulibrary/figgy/blob/9d5676918a71febf2001f1ac8df2fe4049e1f8bf/app/jobs/run_ocr_job.rb#L7)in find_by'
 instrumented_storage_adapter.rb  50  block in trace(...)
[PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb:50:in `block in trace'
 instrumented_storage_adapter.rb  45  trace(...)
[PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb:45:in `trace'
 instrumented_storage_adapter.rb  27  find_by(...)
[PROJECT_ROOT]/app/storage_adapters/instrumented_storage_adapter.rb:27:in `find_by'
 hocr_derivative_service.rb  60  file_object(...)
[PROJECT_ROOT]/app/derivative_services/hocr_derivative_service.rb:60:in `file_object'
 hocr_derivative_service.rb  56  filename(...)
[PROJECT_ROOT]/app/derivative_services/hocr_derivative_service.rb:56:in `filename'
 hocr_derivative_service.rb  26  initialize(...)
[PROJECT_ROOT]/app/derivative_services/hocr_derivative_service.rb:26:in `initialize'
 hocr_derivative_service.rb  13  new(...)
[PROJECT_ROOT]/app/derivative_services/hocr_derivative_service.rb:13:in `new'
 hocr_derivative_service.rb  13  new(...)
[PROJECT_ROOT]/app/derivative_services/hocr_derivative_service.rb:13:in `new'
 run_ocr_job.rb  7  perform(...)
[PROJECT_ROOT]/app/jobs/run_ocr_job.rb:7:in `perform'
```

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/53391/faults/83759049)

**Comment by m-ichelleliu** [comment]
How do we want to handle this error?

**Comment by hackartisan** [comment]
It should rescue and log the error, but do nothing.
