### ISSUE TITLE
Blacklight deprecations 

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#5236]
Individual issues were made for the remainder of these, except the blacklight deprecations coming from within blacklight. More investigation to be done there?

**Comment by hackartisan** [comment]
Here's the original BL issue (took some digging to find) https://github.com/projectblacklight/blacklight/issues/2683

**Comment by hackartisan** [comment]
Remaining blacklight deprecations:

```
DEPRECATION WARNING: search_fields is deprecated and will be removed from a future release (removed without replacement). (called from block in _vendor_bundle_ruby_______gems_blacklight________app_views_catalog_index_json_jbuilder__739734954213199211_414960 at /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/blacklight-7.28.0/app/views/catalog/index.json.jbuilder:70) (4 times); e.g.: 
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/blacklight-7.28.0/app/views/catalog/index.json.jbuilder:70:in `block in _vendor_bundle_ruby_______gems_blacklight________app_views_catalog_index_json_jbuilder__739734954213199211_414960'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:42:in `block in set!'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:296:in `block in _merge_block'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:347:in `_scope'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:296:in `_merge_block'
```
```
DEPRECATION WARNING: search_field_options_for_select is deprecated and will be removed from a future release (removed without replacement). (called from search_fields at /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/blacklight-7.28.0/app/helpers/blacklight/configuration_helper_behavior.rb:25) (4 times); e.g.: 
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/blacklight-7.28.0/app/helpers/blacklight/configuration_helper_behavior.rb:25:in `search_fields'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/blacklight-7.28.0/app/views/catalog/index.json.jbuilder:70:in `block in _vendor_bundle_ruby_______gems_blacklight________app_views_catalog_index_json_jbuilder__739734954213199211_414960'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:42:in `block in set!'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:296:in `block in _merge_block'
    /home/circleci/figgy/vendor/bundle/ruby/2.7.0/gems/jbuilder-2.11.5/lib/jbuilder.rb:347:in `_scope'
```
