### ISSUE TITLE
Error importing Derrida metadata from PULFA

### ISSUE THREAD

**Issue by escowles** [pulibrary/figgy#612]
When trying to pull in remote metadata from PULFA for a Derrida item (e.g., 'RBD1_c10322'), I get the error:

```
INFO -- : [a011557e-ee88-46b1-ab78-df643162d3b8] Processing by ScannedResourcesController#create as HTML
INFO -- : [a011557e-ee88-46b1-ab78-df643162d3b8]   Parameters: {"utf8"=>"✓", "authenticity_token"=>"TKozFDdwao6h9E77eFmI3TszaVLkBuliEGL+RL+dJpQcqAoZriQmaVFIDk4gwPEtqM14i3T8ufi9K0JPz+kmuQ==", "scanned_resource"=>{"title"=>[""], "source_metadata_identifier"=>"RBD1_c10322", "refresh_remote_metadata"=>"1", "rights_statement"=>"http://rightsstatements.org/vocab/NKC/1.0/", "rights_note"=>"", "local_identifier"=>[""], "holding_location"=>"", "pdf_type"=>"gray", "portion_note"=>"", "nav_date"=>"", "member_of_collection_ids"=>[""], "append_id"=>"", "visibility"=>"restricted"}, "mutex_field"=>"RBD1_c10322", "commit"=>"Save"}
INFO -- : [a011557e-ee88-46b1-ab78-df643162d3b8] Completed 500 Internal Server Error in 128ms (ActiveRecord: 2.0ms)
FATAL -- : [a011557e-ee88-46b1-ab78-df643162d3b8]   
FATAL -- : [a011557e-ee88-46b1-ab78-df643162d3b8] Encoding::UndefinedConversionError ("\xC3" from ASCII-8BIT to UTF-8):
FATAL -- : [a011557e-ee88-46b1-ab78-df643162d3b8]   
FATAL -- : [a011557e-ee88-46b1-ab78-df643162d3b8] app/change_set_persisters/plum_change_set_persister.rb:65:in `save'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/change_set_persisters/plum_change_set_persister.rb:89:in `block (2 levels) in buffer_into_index'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/change_set_persisters/plum_change_set_persister.rb:107:in `with'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/change_set_persisters/plum_change_set_persister.rb:88:in `block in buffer_into_index'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/adapters/indexing_adapter.rb:77:in `block (2 levels) in buffer_into_index'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/adapters/indexing_adapter.rb:76:in `block in buffer_into_index'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/adapters/indexing_adapter.rb:75:in `buffer_into_index'
[a011557e-ee88-46b1-ab78-df643162d3b8] app/change_set_persisters/plum_change_set_persister.rb:87:in `buffer_into_index'
INFO -- : ** [Honeybadger] Reporting error id=c43ab8c3-e45a-404c-b899-40dd36f47410 level=1 pid=4052
INFO -- : ** [Honeybadger] Success ⚡ https://app.honeybadger.io/notice/c43ab8c3-e45a-404c-b899-40dd36f47410 id=c43ab8c3-e45a-404c-b899-40dd36f47410 code=201 level=1 pid=4052
```

This looks like a character-encoding issue with accented characters in the PULFA metadata (which is included in the attributes of the ScannedResource)

**Comment by escowles** [comment]
Fixed with https://github.com/pulibrary/figgy/pull/646
