### ISSUE TITLE
Fix "leaking double" spec error

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/figgy#6157]
https://app.circleci.com/pipelines/github/pulibrary/figgy/6872/workflows/23e1a96e-38c2-4aea-8d2c-de3cf1482b6a/jobs/47561

The test failure says:

```

Failures:

  1) CreateDerivativesJob#perform_now triggers a derivatives_created message
     Failure/Error: valid_generators = generators.select { |g| g.valid?(record) }
       #<InstanceDouble(EventGenerator::GeoblacklightEventGenerator) (anonymous)> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
     # ./app/services/event_generator/composite_generator.rb:38:in `block in delegate_to_generator'
     # ./app/services/event_generator/composite_generator.rb:38:in `select'
     # ./app/services/event_generator/composite_generator.rb:38:in `delegate_to_generator'
     # ./app/services/event_generator/composite_generator.rb:27:in `record_updated'
     # ./app/services/event_generator.rb:9:in `record_updated'
     # ./app/change_set_persisters/change_set_persister/publish_message.rb:53:in `run'
     # ./app/change_set_persisters/change_set_persister.rb:246:in `block (2 levels) in after_save_commit'
     # ./app/change_set_persisters/change_set_persister.rb:202:in `add'
     # ./app/change_set_persisters/change_set_persister.rb:245:in `block in after_save_commit'
     # ./app/change_set_persisters/change_set_persister.rb:243:in `each'
     # ./app/change_set_persisters/change_set_persister.rb:243:in `after_save_commit'
     # ./app/change_set_persisters/change_set_persister.rb:119:in `block in save'
     # ./app/change_set_persisters/change_set_persister.rb:114:in `save'
     # ./app/jobs/create_derivatives_job.rb:10:in `perform'
     # ./spec/jobs/create_derivatives_job_spec.rb:18:in `block (3 levels) in <top (required)>'

  2) CreateDerivativesJob#perform_now enqueues a fixity job
     Failure/Error: valid_generators = generators.select { |g| g.valid?(record) }
       #<InstanceDouble(EventGenerator::GeoblacklightEventGenerator) (anonymous)> was originally created in one example but has leaked into another example and can no longer be used. rspec-mocks' doubles are designed to only last for one example, and you need to create a new one in each example you wish to use it for.
     # ./app/services/event_generator/composite_generator.rb:38:in `block in delegate_to_generator'
     # ./app/services/event_generator/composite_generator.rb:38:in `select'
     # ./app/services/event_generator/composite_generator.rb:38:in `delegate_to_generator'
     # ./app/services/event_generator/composite_generator.rb:27:in `record_updated'
     # ./app/services/event_generator.rb:9:in `record_updated'
     # ./app/change_set_persisters/change_set_persister/publish_message.rb:53:in `run'
     # ./app/change_set_persisters/change_set_persister.rb:246:in `block (2 levels) in after_save_commit'
     # ./app/change_set_persisters/change_set_persister.rb:202:in `add'
     # ./app/change_set_persisters/change_set_persister.rb:245:in `block in after_save_commit'
     # ./app/change_set_persisters/change_set_persister.rb:243:in `each'
     # ./app/change_set_persisters/change_set_persister.rb:243:in `after_save_commit'
     # ./app/change_set_persisters/change_set_persister.rb:119:in `block in save'
     # ./app/change_set_persisters/change_set_persister.rb:114:in `save'
     # ./app/jobs/create_derivatives_job.rb:10:in `perform'
     # ./spec/jobs/create_derivatives_job_spec.rb:23:in `block (4 levels) in <top (required)>'
     # ./spec/jobs/create_derivatives_job_spec.rb:23:in `block (3 levels) in <top (required)>'

Finished in 5 minutes 10 seconds (files took 14.92 seconds to load)
887 examples, 2 failures

Failed examples:

rspec ./spec/jobs/create_derivatives_job_spec.rb:17 # CreateDerivativesJob#perform_now triggers a derivatives_created message
rspec ./spec/jobs/create_derivatives_job_spec.rb:22 # CreateDerivativesJob#perform_now enqueues a fixity job
```

**Comment by eliotjordan** [comment]
Can't replicate. Closing.
